name: Deploy to Railway

on:
  push:
    branches: [main]
env:
  TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Print token
        run: echo "${TOKEN}"

      - name: Deploy
        uses: devtomio/action-railway@v1.1.4
        with:
          railway_token: ${TOKEN}
